### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Kipparis** [fluks/mupdf-x11-bookmarks#1]
May you add "how to install" sections into README.md?

**Comment by fluks** [comment]
It should be the same that is in README:
```
git submodule update --init
make
sudo make prefix=/usr/local install
```
But I get errors.

Mupdf has a bookmark feature nowadays in mupdf-gl, I think.

**Comment by fluks** [comment]
I added how to install to readme.

And fixed errrors and updated mupdf too.
